### ISSUE TITLE
Some icons disappear after server reboot

### ISSUE THREAD

**Issue by xRedFox** [TeaSpeak/TeaSpeak#122]
## System Information
***Operating System***:  ArchLinux
***Operating System Type*** (x86|x64):  x86_64
***TeaSpeak Version***: 1.1.25 beta 3

## Issue
***Reason for reporting this issue***:
Bug

***Detailed Description***:
After restarting the server half of server groups icons disappear even if they are still available from the file transfer

[logs.zip](https://github.com/TeaSpeak/TeaSpeak/files/1995153/logs.zip)

**Comment by WolverinDEV** [comment]
Hey,
I already recreated this bug and will fix it soon. 
I'm currently not on Linux and can't work on the server actually (I'm busy at work with the ts patcher plug in for windows)

**Comment by WolverinDEV** [comment]
fixed (just affect group icons)

**Comment by xRedFox** [comment]
The problem still persists in version 1.1.25 beta 6
Logs: [log_2018-05-16_08_38_35_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2007777/log_2018-05-16_08_38_35_general.log)

**Comment by WolverinDEV** [comment]
Which icons bug away?
BTW. The icons don't appear after you upgraded

**Comment by xRedFox** [comment]
All the icons disappeared after the server was updated to beta 6. I put them back and it seems that now the **icons that normally disappeared** (in previous betas) **are now visible and those that were previously visible now disappear**.

The problem occurs on all virtual servers, I take as an example ts port 9987 id 1
**Before Reboot:**
![before](https://user-images.githubusercontent.com/19707386/40109465-b8c01c0c-58fd-11e8-9a40-9789ea5d0853.PNG)

**After Reboot:**
![after](https://user-images.githubusercontent.com/19707386/40109486-bdc585de-58fd-11e8-8401-36b72e9bfb1a.PNG)

These are the icons: [iconsBackup_1_9987.zip](https://github.com/TeaSpeak/TeaSpeak/files/2008464/iconsBackup_1_9987.zip)

**Comment by WolverinDEV** [comment]
Ah fuck i got now the error :D Was a convert error between signed _int32 and unsigned __int32....
Will be fixed as soon im on linux again

**Comment by WolverinDEV** [comment]
fixed again :D (Tested by myself with your icons :))
