### ISSUE TITLE
I must connect two times

### ISSUE THREAD

**Issue by EnderPixel** [TeaSpeak/TeaSpeak#242]
## System Information
***Operating System***:
***Operating System Type*** (x86|x64):
***TeaSpeak Version***:

## Issue
***Reason for reporting this issue***:
When i connect there is connection errror but when i connect two times there is no connection error why it is so?

***Detailed Description***:

*Delete me: If you dont follow this issue template, you may not get a response or the issue get instandly closed.*

**Comment by MikkelDK** [comment]
Do you have try updated the server? ;)

2018-07-24 13:16 GMT+02:00 EnderPixel <notifications@github.com>:

**Comment by EnderPixel** [comment]
I cant update the server i host it not by my self. The server is hostet by server-sponsoring.com

**Comment by MikkelDK** [comment]
So ask them to update the server? ;) there is nothing we can do. There have
been fixed the issue with connection issue. ;)

2018-07-24 13:18 GMT+02:00 EnderPixel <notifications@github.com>:

**Comment by EnderPixel** [comment]
Ok i try to contact them. I thinked it was a bug in tespeak.

**Comment by MikkelDK** [comment]
#232 you can read there.. it has been fixed. ;)

**Comment by EnderPixel** [comment]
ok thanks good day :)

**Comment by daffyyyy** [comment]
Linux x64 | 1.1.41-beta-2 and problem not solved, i too have problem with 2 times connection

**Comment by WolverinDEV** [comment]
Please read my last post in the other topic.
Because of duplication I'll close this one

**Comment by WolverinDEV** [comment]
Duplicate of #232
