### ISSUE TITLE
Invisible / silent

### ISSUE THREAD

**Issue by nkleinert** [TeaSpeak/TeaSpeak#326]
**Describe the bug**
Hello, since the latest version there are again the problems you can't hear others and sometimes you can't see them.

**Environment information:**
 Operating system: Linux ubuntu 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
 TeaSpeak version: 1.2.10b

**Comment by WolverinDEV** [comment]
Is there any proof?

**Comment by MikkelDK** [comment]
You need to come with proof of logs/screenshots ;)

**Comment by Chazotu** [comment]
Can confirm for TeaSpeak version: 1.2.10b4 will test it later for b5

**Comment by Najsr** [comment]
Can confirm on build 5. My friend was visible and I moved him to another room which i was subscribed to + enough subscribe power. When I moved him log gave me:
<14:48:13> "UserX" left heading to channel "Users's Room"
But when I moved him back What I only got was disconnect:
<14:49:03> Disconnected from server (parameter not found)

**Comment by Najsr** [comment]
Log from ts3hook:
[OUT] Blocking connectioninfoautoupdate
[IN ] error id=0 msg return_code=th
PLUGIN: onServerErrorEvent 1  0 th
[IN ] notifyclientleftview reasonmsg=view\sleft reasonid=0 clid=23 cfid=247 ctid=11144
[OUT] Blocking connectioninfoautoupdate
[OUT] Blocking connectioninfoautoupdate
[IN ] error id=0 msg return_code=th
PLUGIN: onServerErrorEvent 1  0 th

**Comment by Najsr** [comment]
```
20.08.18 15:08:55		Debug	[User_1] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_1] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_3] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_3] Failed to handle acknowledge: Missing packet id (321)	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_1] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:55		Debug	[Permission]    Permission: i_channel_description_view_power Required value: 0 Gained value: 50 Force required: 0 Channel: jouu Result: 1	
20.08.18 15:08:55		Debug	[User_1] Resend 1 packets	
20.08.18 15:08:55		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:55		Debug	[Permission]    Permission: i_channel_description_view_power Required value: 0 Gained value: 50 Force required: 0 Channel: jouu Result: 1	
20.08.18 15:08:55		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:55		Debug	[Permission]    Permission: i_channel_description_view_power Required value: 0 Gained value: 50 Force required: 0 Channel: jouu Result: 1	
20.08.18 15:08:55		Debug	[User_1] Failed to handle acknowledge: Missing packet id (155)	
20.08.18 15:08:55		Debug	[User_1] Failed to handle acknowledge: Missing packet id (157)	
20.08.18 15:08:55		Debug	[User_1] Failed to handle acknowledge: Missing packet id (158)	
20.08.18 15:08:55		Debug	[User_1] Failed to handle acknowledge: Missing packet id (157)	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_1] Failed to handle acknowledge: Missing packet id (158)	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:55		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 322 of type Command	
20.08.18 15:08:56		Debug	[User_4] Closing voice client connection. (Flush: true)	
20.08.18 15:08:56		Debug	[User_4] Awaiting write prepare, write and acknowledge queue flushed	
20.08.18 15:08:56		Debug	[User_4] Write prepare queue progressed	
20.08.18 15:08:56		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 323 of type Command	
20.08.18 15:08:56		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:56		Debug	[Permission]    Permission: i_channel_description_view_power Required value: 0 Gained value: -2 Force required: 0 Channel: Channel_1 Result: 1	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 322 of type Command	
20.08.18 15:08:56		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 323 of type Command	
20.08.18 15:08:56		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:56		Debug	[Permission]    Permission: b_channel_join_permanent Required value: 1 Gained value: 1 Force required: 0 Channel: Channel_1 Result: 1	
20.08.18 15:08:56		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:56		Debug	[Permission]    Permission: b_channel_join_ignore_maxclients Required value: 1 Gained value: -2 Force required: 1 Channel: Channel_1 Result: 0	
20.08.18 15:08:56		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:56		Debug	[Permission]    Permission: i_channel_join_power Required value: 0 Gained value: -2 Force required: 0 Channel: Channel_1 Result: 1	
20.08.18 15:08:56		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:56		Debug	[Permission]    Permission: b_channel_ignore_view_power Required value: 1 Gained value: -2 Force required: 1 Channel: none Result: 0	
20.08.18 15:08:56		Debug	[User_5] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 322 of type Command	
20.08.18 15:08:56		Debug	[User_6] Got a channel talk power of 0 Talk power set is 0	
20.08.18 15:08:56		Debug	[User_3] Resend 1 packets	
20.08.18 15:08:56		Error	Command handling of command clientmove needs 39ms	
20.08.18 15:08:56		Error	[User_6] Handling of packet Command needs more than 10ms (39ms)	
20.08.18 15:08:56		Debug	[User_7] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 323 of type Command	
20.08.18 15:08:56		Debug	[User_5] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_1] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_7] Failed to handle acknowledge: Missing packet id (324)	
20.08.18 15:08:56		Debug	[User_3] Failed to handle acknowledge: Missing packet id (322)	
20.08.18 15:08:56		Debug	[User_1] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_5] Failed to handle acknowledge: Missing packet id (1291)	
20.08.18 15:08:56		Debug	[User_5] Failed to handle acknowledge: Missing packet id (1292)	
20.08.18 15:08:56		Debug	[User_1] Failed to handle acknowledge: Missing packet id (163)	
20.08.18 15:08:56		Debug	[User_1] Failed to handle acknowledge: Missing packet id (164)	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:56		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:57		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 322 of type Command	
20.08.18 15:08:57		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 323 of type Command	
20.08.18 15:08:57		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 322 of type Command	
20.08.18 15:08:57		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 323 of type Command	
20.08.18 15:08:57		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:57		Debug	[User_2] Resend 1 packets	
20.08.18 15:08:57		Debug	[Permission] Value test result for test type 1.	
20.08.18 15:08:57		Debug	[Permission]    Permission: i_channel_description_view_power Required value: 0 Gained value: -2 Force required: 0 Channel: Volná místnost #1 Result: 1	
20.08.18 15:08:57		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 322 of type Command	
20.08.18 15:08:57		Debug	[User_4] Failed to execute packet resend: Failed to receive acknowledge for packet 323 of type Command	
20.08.18 15:08:57		Debug	[User_4] Cant flush io!	
20.08.18 15:08:57		Debug	[User_4] Could not get acknowledge for all commands before disconnecting. Acknowledges left: 2	
20.08.18 15:08:57		Info	Voice client /DZRt7yZNSWzxZwuU= (USERX) from HIS_IP left.	
20.08.18 15:08:57		Debug	Updating server property: virtualserver_last_client_disconnect. New value: 1534770537. Query: UPDATE `properties` SET `value` = :value WHERE `serverId` = :sid AND `type` = :type AND `id` = :id AND `key` = :key	
```
Some logs regarding that from server

**Comment by Najsr** [comment]
@WolverinDEV Wrote PM on your forum

**Comment by nkleinert** [comment]
Sorry for the late answer. Here's my log:

> [2018-08-19 20:55:39] [INFO]      3 | Voice client USER_UID (USER_NAME) from USER_IP:38752 left.
[2018-08-19 20:55:39] [DEBUG]     3 | Updating server property: virtualserver_last_client_disconnect. New value: 1534704939. Query: UPDATE `properties` SET `value` = :value WHERE `serverId` = :sid AND `type` = :type AND `id` = :id AND `key` = :key
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:58227/USER_NAME] Awaiting write prepare, write and acknowledge queue flushed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:58227/USER_NAME] Write prepare queue progressed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:65203/USER_NAME] Awaiting write prepare, write and acknowledge queue flushed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:65203/USER_NAME] Write prepare queue progressed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Awaiting write prepare, write and acknowledge queue flushed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Write prepare queue progressed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Awaiting write prepare, write and acknowledge queue flushed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Write prepare queue progressed
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:60300/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:65203/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:58227/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:49639/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:56613/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:40935/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:58896/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:40743/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:51444/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:60969/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55073/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53885/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:59843/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:60300/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53885/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:49639/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:40935/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:40743/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:59843/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:60969/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:65203/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:58227/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55073/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:56613/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:51444/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:58896/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:60300/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53885/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:49639/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:40935/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:40743/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:59843/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:60969/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:65203/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:58227/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:55073/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:60300/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Resend 1 packets
[2018-08-19 20:55:39] [DEBUG]     3 | [USER_IP:53885/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:49639/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:40935/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:56613/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:51444/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:58896/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:40743/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:59843/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:60969/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:65203/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:58227/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:60300/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:53885/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:49639/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:40935/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55073/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:56613/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:51444/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:40743/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:59843/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:60969/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:65203/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:58896/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:60300/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:53253/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:53885/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:49639/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:58227/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:40935/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55073/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:61625/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:52318/USER_NAME] Resend 1 packets
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Cant flush io!
[2018-08-19 20:55:40] [DEBUG]     3 | [USER_IP:55545/USER_NAME] Could not get acknowledge for all commands before disconnecting. Acknowledges left: 1
[2018-08-19 20:55:40] [INFO]      3 | Voice client USER_UID (USER_NAME) from USER_IP:55545 left.

**Comment by WolverinDEV** [comment]
I meant also the log from before the disconnect.
When you moved him and back again :)

**Comment by nkleinert** [comment]
I didn't even notice the bug. It was just told to me, and an approximate time. That's why I can't help you that well.

**Comment by Najsr** [comment]
Do you want client log?

**Comment by WolverinDEV** [comment]
Should be fixed within version 1.2.10-beta!

**Comment by nkleinert** [comment]
Hey, the same problem with the current version. He's (a friend) on our channel, but we can't hear or see him. But he can see and hear us. There's nothing in the logs either.

**Comment by katrio022** [comment]
Problem is still not fixed, described here:
https://forum.teaspeak.de/index.php?threads/problem-with-bans.525/post-3491

**Comment by almir101** [comment]
Yet same problem is happening,even on latest version of TeaSpeak server ( TeaSpeak-1.2.12-beta ).
I would like to participate if possible to solve this issue.

**Comment by h1rule** [comment]
Maybe some Channel permissions?

**Comment by almir101** [comment]
Nope,
When client fast makes fast switch between two or more channels it becomes invisible.
I have tested it with sinusbot to reproduce this bug.
I installed "Back to default +" script on sinusbot,moved bot to my channel,and when I leave channel,
Bot "vanishes" from the server.
Same thing happens when I move the bot to the empty channel and he automatically goes to the default channel,and it becomes invisible for some reason.

**Comment by WolverinDEV** [comment]
Hmm well it seems like a great bug report.
And I guess when he is invisible you also may get the invalid or missing parameter disconnect?

**Comment by almir101** [comment]
Nope,it stays on server,but not visible for me until I reconnect to the server.
No disconnect message appears.

**Comment by WolverinDEV** [comment]
Should be fixed now :) (Helped issue #370)
