### ISSUE TITLE
Channelgroup talk power. Not updating

### ISSUE THREAD

**Issue by SafariGaming** [TeaSpeak/TeaSpeak#341]
https://ibb.co/g5Vjvz
https://ibb.co/chbPvz
https://ibb.co/fZsa2e

**Comment by WolverinDEV** [comment]
Please use the general issue form!
BTW: It was already fixed versions ago...

**Comment by SafariGaming** [comment]
My English is not good. I don't understand what you wrote on the form. I am already using last version "Linux x64 | 1.2.11-beta-1". Not fixed this !
