### ISSUE TITLE
[Advice/Potential bug] Permission issue

### ISSUE THREAD

**Issue by slushpuppy** [TeaSpeak/TeaSpeak#517]
Today I came onto one of my servers and apparently Server Admin permissions was so screwed up that it wasn't even able to edit permission like group_sort_id without throwing an error:

insufficient client permissions (failed on i_permission_modify_power)

Strangely enough, other permissions such as setting kick powers was OK.

Resetting the server with permreset solved the issue but I am wondering what could have been done in the first place to cause this issue?

**Comment by slushpuppy** [comment]
Yes I am using beta 2.

After the reset of the TS, same problem occurred again, but all instances this appears to be caused by the serveradmin messing around with the permissions, it's not the data loss as my other servers that are managed by people who know ts permissions haven't encountered this issue at all.

Is it possible to make serveradmin override all permissions regardless of the settings?

**Comment by Sephiara** [comment]
> Is it possible to make serveradmin override all permissions regardless of the settings?

Really? Then you can't set any lower SA rights.
I don't have this issue, also it´s your failure :P

In my oppinion had a adminquery delete the permission from your servergroups, or at the main serveradmin group (ID 3). Check this out and activate it.

BTW: Reset your TeaSpeakServer installation again, use newest version and don't backup/snapshot the old serverinstances.

**Comment by WolverinDEV** [comment]
Is here still any issue or had everything been solved by time?

**Comment by slushpuppy** [comment]
Yes, this issue still crops up time to time, for example:

![image](https://user-images.githubusercontent.com/1729407/51804043-be05ca00-2296-11e9-9631-ff251661d271.png)

but when adding permissions to b_client_music_create_temporary

insufficient client permissions (failed on i_permission_modify_power)

this pops up
