### ISSUE TITLE
[BUG]Cant decrypt packet of type Voice. Dropping packet. Error: memory verify failed

### ISSUE THREAD

**Issue by Crosus97** [TeaSpeak/TeaSpeak#556]
**Describe the bug**
im haveing problems with my server and the users report they sometimes can not talk
they are not muted, the server dont transmit then voices in the channel and other users in the channel can ear then, can be my friend, can be other user, can be me(im through lan).

one of the users had a problem, and I looked in the log, and I found about a constant message of  this error:

**[+++.+++.+++.+++:+++++/Username | 4] Cant decrypt packet of type Voice. Dropping packet. Error: memory verify failed!**

**To Reproduce**
i dont know, random one user suffer 

**Screenshots**

**Logs**
I censure the ip and name of my user
[log.txt](https://github.com/TeaSpeak/TeaSpeak/files/2796202/log.txt)

**Environment information:**
 Operating system: (`linux`)
 TeaSpeak version: [TeaSpeak Server-1.3.3 beta 1]
 I am using `experimental_31`: yes

**Additional context**

**Comment by WolverinDEV** [comment]
I think that the
```
Cant decrypt packet of type Voice. Dropping packet. Error: memory verify failed
```
isn't the cause for the voice bug.
I've heard there should be a kind of mute bug where you cant speak, because everybody thinks you're muted.
I'm currently lokking at this bug

**Comment by Crosus97** [comment]
I think I can confirm very surely that the error is that. this took me 3 days and one end noticing when a user can not "speak", so on 2 or 3 occasions I told them not to disconnect yet and when I looked at the log, they had the same error message, same but with different ips and different names obviously, I have not found any other co-incidents,
the only way to fix it was to reconnect

**Comment by Crosus97** [comment]
still happening any help ?

**Comment by WolverinDEV** [comment]
May improved in 1.3.6b

**Comment by REDOSS** [comment]
@WolverinDEV 
1.3.6 
> Cant decrypt packet even with default key! Type: Ack, Error: memory verify failed!, Packet ID: 0, Generation: 0

**Comment by WolverinDEV** [comment]
Just once or continues?
If just once or twice then all right.

**Comment by REDOSS** [comment]
Repeated for some users. I'll write the report later.

**Comment by REDOSS** [comment]
[log_2019-02-03_04%3A25%3A23_general.log](https://github.com/TeaSpeak/TeaSpeak/files/2825765/log_2019-02-03_04.3A25.3A23_general.log)

**Comment by jonipin** [comment]
Still happening on my server! In fact it started happening to me when i updated today to the latest Version...

Dunno wut to do...

**Comment by jonipin** [comment]
Well Just downgraded to 1.2.33.B3 and it's fine! No bug whatsoever

**Comment by Crosus97** [comment]
I what version you start?

**Comment by jonipin** [comment]
I was on 1.2.33 no Bugs! Then i upgraded to 1.3.7 and the bug started happening so i rolled back the update to 1.2.33 and that solved the problem

**Comment by WolverinDEV** [comment]
1.3.7 should be become Better

**Comment by Crosus97** [comment]
you need more information about this ?? i need to update TeaSpeak
i have my server on a virtualmachine on HyperV, if you want...

**Comment by concuncan** [comment]
@WolverinDEV I can confirm this issue still occurs in 1.3.7-beta. I'll upload the log file as soon as it happens again so you can take a look into it.

**Comment by Crosus97** [comment]
this bug is fixed?

**Comment by Sickness-chan** [comment]
No, and it's the same issue as https://github.com/TeaSpeak/TeaSpeak/issues/575

**Comment by chronicals** [comment]
Still having this issue and it's turning users away from our servers.

**Comment by Sickness-chan** [comment]
@WolverinDEV is this getting looked into?

**Comment by WolverinDEV** [comment]
fixed in 1.3.17 :)
Thanks for all of your support!
